### ISSUE TITLE
There is someting wrong when test

### ISSUE THREAD

**Issue by mingming36** [SY-Xuan/IICS#10]
File "/home/l603a/mrp/II/reid/evaluators_cos.py", line 62, in pairwise_distance
    x = torch.cat([features[f].unsqueeze(0) for f, _, _ in query], 0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]

**Comment by SY-Xuan** [comment]
Could you provide me with more information. e.g., how you run the code.

**Comment by mingming36** [comment]
I run the command python ./example/iics.py --dataset market1501 --checkpoint "/home/l603a/mrp/II/script/papa/market.pth.tar" --evaluate

**Comment by mingming36** [comment]
I run the commandpython ./example/iics.py --dataset market1501 --checkpoint "/home/l603a/mrp/II/script/papa/market.pth.tar" --evaluate, because of thr edition of pytorch?

**Comment by SY-Xuan** [comment]
I think maybe the setting of the dataset file path is wrong. You can check the dataset dir.

**Comment by mingming36** [comment]
ok,thanks.
