### ISSUE TITLE
mAP is low on a different dataset

### ISSUE THREAD

**Issue by faisalimran2018** [SY-Xuan/IICS#13]
We have fine-tuned the proposed model on our dataset (Similar to market1501) using the same parameters except for the batch size [batch_size=4, batch_size_stage2=16] but the mAP of the model is low 39.1 which is quite low moreover the rank-1 accuracy was 86.5. Can you please guide me on this?

**Comment by SY-Xuan** [comment]
The batch size is very important hyper parameter to our method. For example, the small batch size can strongly influence the calculation of BN leading to the poor performance. I think you need to enlarge your batch size. What`s more, the performance of different datasets is not comparable. Your dataset may be very difficult or the size of your dataset is small. All these aspects can influence the performance of your model.
