### ISSUE TITLE
Unable to extract the trained models. 

### ISSUE THREAD

**Issue by ElsaLuz** [SY-Xuan/IICS#3]
@SY-Xuan 
Hi! 
I am unable to extract the trained models. 
It gives me this error:
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
And in Windows:
```
The achieve is either in unknown format or damaged.
```
I tried to repair them as well, but I am getting these errors again:
```
! C:\Users\Desktop\duke.pth.tar: Unexpected end of archive
! C:\Users\Desktop\duke.pth.tar: Corrupt header is found
! C:\Users\Desktop\duke.pth.tar: No files repaired
```

**Comment by SY-Xuan** [comment]
This file is not in tar format. You can use it directly through pytorch.
`
torch.load("duke.pth.tar")
`

**Comment by ElsaLuz** [comment]
Hi again!
As, you have mentioned in the Readme:

>  You need to download ResNet-50 imagenet pretrained model and change the checkpoint path in the ./script/train_market.sh

Could you please tell me, where can I find `checkpoint_path`?
Thank you!

**Comment by SY-Xuan** [comment]
You can find it in the source code of torchvision.

**Comment by SY-Xuan** [comment]
@ElsaLuz If you don`t have any other questions, I will close this issue.

**Comment by ElsaLuz** [comment]
@SY-Xuan Thank you for your time and support. I'll re-open this issue if I encounter any problem again.

**Comment by ElsaLuz** [comment]
@SY-Xuan 
Hi again!
Could you please mention the resource utilization? That is, how much of the disk space, RAM and how many GPUs were used for training on each dataset? 
In the paper you have mentioned that "It takes about 4-5 hours to finish the training with a GPU on Market1501". Do you mean only one GPU was used? 
If possible kindly mention the time taken by each dataset for training.

Regards

**Comment by SY-Xuan** [comment]
We use only one single Titan RTX. It takes about 4-5 hours on Market1501, 6-8 hours on DukeMTMC and 20 hours on MSMT17.

**Comment by ElsaLuz** [comment]
@SY-Xuan 
I need recommendations for my system up-gradation. When I try to run your code for dukemtmc dataset my 12 GB of RAM gets utilized completely after 15 minutes of training. After 15 minutes I get tcmalloc error. When I try to run for market-1501, I get this output after 9 epochs (and 2.5 hours of training):
```
.
.
.
Starting re_ranking...
./script/train_market.sh: line 2:  2499 Killed
.
.
.
```
So, what other system requirements do I need to run your model?  Please do recommend me the system requirements so I can work error-free. 
Regards

**Comment by ElsaLuz** [comment]
I don't get it, DukeMTMC in zip is of 140MB and Market-1501 is of 145MB. Furthermore, batch training is used. Then why doesn't training get completed, if I use 12GB of RAM. Is your architecture deep, having large number of parameters? Could you please give an insight of the number of parameters of your architecture? I tried to decrease the batch size to 32 as well (for Market-1501) but the problem still persists.

**Comment by ElsaLuz** [comment]
@SY-Xuan 
I have successfully trained on **DukeMTMC** with **15 identities** only for train and test sets and **7 identities** for **query** set. As well as, changed **workers** and **instances** to **1**. But now when I am trying to evaluete the model, I get this error:
```
Namespace(batch_size=8, batch_size_stage2=64, checkpoint='/root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth', class_number_stage1=13, class_number_stage2=15, cluster_epochs=40, data_dir='/content/IICS/example/data', dataset='dukemtmc', decay_factor=0.6, epochs_stage1=2, epochs_stage2=2, evaluate=True, height=None, instances=1, linkage='average', logs_dir='/content/IICS/example/logs', lr=0.005, margin=0.3, mix_rate=0.02, momentum=0.9, multi_task_weight=1.0, print_freq=20, seed=1, split=0, start_save=0, stride=1, use_cpu=False, warm_up=0, weight_decay=0.0005, width=None, workers=1)
Files already downloaded and verified
DukeMTMC dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |    13 |      343
  val      |     2 |       29
  trainval |    15 |      372
  query    |     7 |       25
  gallery  |    15 |      346
=> Loaded checkpoint '/root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth'
Traceback (most recent call last):
  File "./example/iics.py", line 394, in <module>
    main(parser.parse_args())
  File "./example/iics.py", line 143, in main
    for k, v in checkpoint['state_dict'].items():
KeyError: 'state_dict'
```
Could you please point out what am I doing wrong , here? 
Thank you!

**Comment by SY-Xuan** [comment]
It seems that your computer don`t have enough RAM (Memory not the GPU Memory). I run this code on a server which has 128G RAM.

**Comment by ElsaLuz** [comment]
Oh! okay. Thank you for the information.
