### ISSUE TITLE
msmt17

### ISSUE THREAD

**Issue by gzw820** [SY-Xuan/IICS#5]
When I evaluate the msmt17 dataset, I run "sh ./script/test_msmt.sh" in the terminal. However, something is wrong with it, and it indicates that "FileNotFoundError: [Error:2] No such file or dictory: XXX/example/data/msmt17/raw/list_train.txt''.  After I add a empty "list_train.txt" in the raw dictory. It still doesnot run . Could help me solve it?

**Comment by SY-Xuan** [comment]
I think you may use the wrong version of MSMT17. The version you use don`t have the list_train.txt. By the way, I use the MSMT17_V2.

**Comment by gzw820** [comment]
Ok，thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SY-Xuan/IICS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SY-Xuan/IICS] msmt17 (#5)





 
I think you may use the wrong version of MSMT17. The version you use don`t have the list_train.txt. By the way, I use the MSMT17_V2.

**Comment by SY-Xuan** [comment]
You can get the dataset from http://www.pkuvmc.com/dataset.html.

**Comment by gzw820** [comment]
Firstly, thank you very! However, the dataset of MSMT17_V2 cannot be acquired from the link you provide. It is "404 notfound" in the link.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SY-Xuan/IICS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SY-Xuan/IICS] msmt17 (#5)





 
You can get the dataset from http://www.pkuvmc.com/dataset.html.

**Comment by SY-Xuan** [comment]
You can send email to Prof. Zhang to ask for the download link of the dataset.

**Comment by ElsaLuz** [comment]
@SY-Xuan I am facing this problem too, when I run:
```
sh ./script/train_msmt.sh
```
Even though, I have MSMT17_V2 dataset. 
Could you please suggest a solution?

**Comment by SY-Xuan** [comment]
I think I made some mistake here. Could you please provide me with the structure of directory here.

**Comment by ElsaLuz** [comment]
@SY-Xuan 
Structure of the dataset **MSMT17_V2** directory is as follows:
```
MSMT17_V2
├── __MACOSX
│   └── MSMT17_V2
|        └──mask_test_v2
|        |      └──0000
|        |      |       └── ._0000_002_01_0303morning_0016_2.jpeg
|        |      |       └──._.DS_Store
|        |      └── . . .
|        |      └──0253
|        |      |       └──._0253_002_01_0303morning_1475_1.jpeg
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──mask_train_v2
|        |      └──0000
|        |      |       └── ._0000_000_01_0303morning_0008_0.jpeg
|        |      |       └──._0000_001_01_0303morning_0008_0_ex.jpeg
|        |      |       └──._0000_013_04_0303morning_0020_2.jpeg
|        |      |       └──._0000_050_12_0303morning_0008_0_ex.jpeg
|        |      |       └──._.DS_Store
|        |      └── . . .
|        |      └──0086
|        |      |       └──._0086_000_01_0303morning_1493_3.jpeg
|        |      |       └──._0086_020_14_0303morning_1718_3_ex.jpeg
|        |      |       └──._0086_021_14_0303morning_1720_1.jpeg
|        |      |       └──._0086_023_14_0303morning_1721_1.jpeg
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──._.DS_Store
|        └──._list_gallery
|        └──._list_query
|        └──._list_train
|        └──._list_val
├── MSMT17_V2
│   └── MSMT17_V2
|        └──mask_test_v2
|        |      └──0000
|        |      |       └──0000_000_01_0303morning_0015_0.jpeg
|        |      |       └──. . . 
|        |      |       └──._.DS_Store
|        |      └── . . .
|        |      └──3059
|        |      |       └──3059_000_13_0113noon_1695_0.jpeg
|        |      |       └──. . . 
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──mask_train_v2
|        |      └──0000
|        |      |        └──0000_000_01_0303morning_0008_0.jpeg
|        |      |        └──. . . 
|        |      |        └──._.DS_Store
|        |      └── . . .
|        |      └──1040
|        |      |       └──1040_000_12_0302morning_0116_6.jpeg
|        |      |       └──. . .
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──._.DS_Store
|        └──._list_gallery
|        └──._list_query
|        └──._list_train
|        └──._list_val 
```

**Comment by SY-Xuan** [comment]
Where you download these files? I think this is not the official version of MSMT17. lol!

**Comment by SY-Xuan** [comment]
![image](https://user-images.githubusercontent.com/22125606/114964844-1b02f000-9ea2-11eb-959c-74077e867c13.png)

**Comment by SY-Xuan** [comment]
![image](https://user-images.githubusercontent.com/22125606/114964900-34a43780-9ea2-11eb-8cf8-600fef582e2e.png)

**Comment by ElsaLuz** [comment]
@SY-Xuan I made a mistake above, while copying the file names. Here is the updated structure:
```
MSMT17_V2
├── __MACOSX
│   └── MSMT17_V2
|        └──mask_test_v2
|        |      └──0000
|        |      |       └── ._0000_002_01_0303morning_0016_2.jpeg
|        |      |       └──._.DS_Store
|        |      └── . . .
|        |      └──0253
|        |      |       └──._0253_002_01_0303morning_1475_1.jpeg
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──mask_train_v2
|        |      └──0000
|        |      |       └── ._0000_000_01_0303morning_0008_0.jpeg
|        |      |       └──._0000_001_01_0303morning_0008_0_ex.jpeg
|        |      |       └──._0000_013_04_0303morning_0020_2.jpeg
|        |      |       └──._0000_050_12_0303morning_0008_0_ex.jpeg
|        |      |       └──._.DS_Store
|        |      └── . . .
|        |      └──0086
|        |      |       └──._0086_000_01_0303morning_1493_3.jpeg
|        |      |       └──._0086_020_14_0303morning_1718_3_ex.jpeg
|        |      |       └──._0086_021_14_0303morning_1720_1.jpeg
|        |      |       └──._0086_023_14_0303morning_1721_1.jpeg
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──._.DS_Store
|        └──._list_gallery
|        └──._list_query
|        └──._list_train
|        └──._list_val
├── MSMT17_V2
│   └── MSMT17_V2
|        └──mask_test_v2
|        |      └──0000
|        |      |       └──0000_000_01_0303morning_0015_0.jpeg
|        |      |       └──. . . 
|        |      |       └──._.DS_Store
|        |      └── . . .
|        |      └──3059
|        |      |       └──3059_000_13_0113noon_1695_0.jpeg
|        |      |       └──. . . 
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──mask_train_v2
|        |      └──0000
|        |      |        └──0000_000_01_0303morning_0008_0.jpeg
|        |      |        └──. . . 
|        |      |        └──._.DS_Store
|        |      └── . . .
|        |      └──1040
|        |      |       └──1040_000_12_0302morning_0116_6.jpeg
|        |      |       └──. . .
|        |      |       └──._.DS_Store
|        |      └──._.DS_Store
|        └──.DS_Store
|        └──list_gallery
|        └──list_query
|        └──list_train
|        └──list_val 
```
And yes, I do have the above files too in ./mask_train_v2/1040 and there are a total of 274 images in this folder.

**Comment by SY-Xuan** [comment]
I recommand you to ask for Prof. Zhang to get the original version of MSMT17. The file structure here still looks somehow strange.

**Comment by ElsaLuz** [comment]
> I recommand you to ask for Prof. Zhang to get the original version of MSMT17. The file structure here still looks somehow strange.

Okay. Thank you.
