### ISSUE TITLE
intra training part code issue

### ISSUE THREAD

**Issue by zhustrong** [SY-Xuan/IICS#6]
Hi, https://github.com/SY-Xuan/IICS/blob/main/reid/models/ft_net.py#L40
This line code num is the ID number, but in paper is cam number. Could you help for this?

**Comment by SY-Xuan** [comment]
I am sorry to make this part confusing. The num_classes is a list which stores the ID number of each camera.
Please see detail at these lines:
 `model = models.create("ft_net_intra",
                              num_classes=[
                                  dt.classes_num for dt in cluster_datasets],
                              stride=args.stride)`

**Comment by zhustrong** [comment]
> I am sorry to make this part confusing. The num_classes is a list which stores the ID number of each camera.
> Please see detail at these lines:
> `model = models.create("ft_net_intra", num_classes=[ dt.classes_num for dt in cluster_datasets], stride=args.stride)`

thanks a lot!
