### ISSUE TITLE
A question about baseline

### ISSUE THREAD

**Issue by zhustrong** [SY-Xuan/IICS#7]
One motivation about this paper is that the pseudo-labels of different cameras are not reliable, which just like show in Fig1.  But actually I use TSNE visualize our own model and some open source model(such as Fast ReID), I didn't find that the ReID features distance of same cameras are closer than diff cameras. 
So, my question is:   Is the convergence of the baseline model not very good?  or This issue only exist in Unsupervised ReID task?

**Comment by SY-Xuan** [comment]
At begining of the training, for example if you use the imagenet pre-trained model to extract features to calculate the similarity between samples, the similarity between different cameras is not reliable. Using similarity like this will make the pseudo-labels unreliable. On the other hand, it is difficult to make the same person from different cameras into the same cluster. At supervised learning, we don't need to generate labels. Therefore, this issue only exists in unsupervised ReID task.
