### ISSUE TITLE
Why re_ranking() the cross_cam_dist/dist of features?

### ISSUE THREAD

**Issue by AFangCCC** [SY-Xuan/IICS#8]
Firstly, thanks for opening source your code! 
I notice that the dist matrix is processed by re_ranking() function before cluster instead of original dist matrix. But I don't understand the reason.

**Comment by SY-Xuan** [comment]
It is a commonly used trick in unsupervised ReID. Re-ranking can improve the similarity between samples, leading to a more reliable similarity. Therefore, the quality of generated pseudo-labels can be improved.

**Comment by AFangCCC** [comment]
> It is a commonly used trick in unsupervised ReID. Re-ranking can improve the similarity between samples, leading to a more reliable similarity. Therefore, the quality of generated pseudo-labels can be improved.

Thanks
