### ISSUE TITLE
The distribution of similarity on DukeMTMC-ReID

### ISSUE THREAD

**Issue by wanglinourin** [SY-Xuan/IICS#9]
In the first discussion, What is the mean of Y-axis please？In the After intra-camera Training, why the green height is different from another methods?

**Comment by SY-Xuan** [comment]
This is a histogram of similarity. Therefore Y-axis denotes the number of data in the bin.
Similarities are normalized into [0, 1] and the range represented by the y-axis is different.
We only want to show an intuitive visualization of real data but different figures are not comparable.
